# Build the manuscript outputs from paper/paper.md: a plain docx, a self-contained html, and the
# journal-neutral submission manuscript (docx, Nature numbered citation style, reference.docx).
# Toolchain: pandoc 3.9, installed via pypandoc_binary (pip install pypandoc_binary; the wheel bundles
# the pandoc binary). Set $env:PANDOC to that binary's path if pandoc is not on PATH.
# Citation style: paper/csl/nature.csl, downloaded 2026-09-24 from
#   https://raw.githubusercontent.com/citation-style-language/styles/master/nature.csl
#   last commit touching nature.csl: e0aa3018cd24b7be9a0e2acf3f9d83a6a78d8f0f (2026-09-08)
#   styles repository master at download: 8947960dc3c5133a873d77342c77c67300a2bc18
# Word template: paper/templates/reference.docx, generated by paper/templates/make_reference_docx.py
#   (Times New Roman 12 pt, 1.5 spacing, A4, 2.5 cm margins, page numbers, continuous line numbers).
# paper/templates/frontmatter.lua prints the affiliation, corresponding author and keywords, which
#   pandoc's default docx template ignores.
# Run from the repository root. Outputs go to paper/build/ (gitignored).
# The resource path holds the directory of refs.bib (paper) and the repository root (figures/).
# ";" separates resource-path entries on Windows.
$ErrorActionPreference = "Stop"

$pandoc = if ($env:PANDOC) { $env:PANDOC } else { "pandoc" }
New-Item -ItemType Directory -Force paper/build | Out-Null

& $pandoc paper/paper.md --resource-path="paper;." --citeproc -o paper/build/paper.docx
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
& $pandoc paper/paper.md --resource-path="paper;." --citeproc --standalone --embed-resources -o paper/build/paper.html
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
& $pandoc paper/paper.md --resource-path="paper;." --citeproc --csl=paper/csl/nature.csl `
  --reference-doc=paper/templates/reference.docx --lua-filter=paper/templates/frontmatter.lua `
  -o paper/build/PaperA_manuscript.docx
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
